# 重回帰分析
目的変数 $y$ を複数の変数 $x_1, x_2, ... , x_n$ で予測する

## モデル
目的変数 $y$ と変数 $x_1, x_2, \cdots, x_M$ の関係を下記の一次式で表せるとする
$$
    y = {w_1}{x_1} + {w_2}{x_2} + \cdots + {w_M}{x_M} + b
$$
これについて最適な $w_1, w_2, \cdots, w_M$ 及び $b$ を求める。  
ここで $w_1, w_2, \cdots, w_M$ は変数 $x_1, x_2, \cdots, x_M$ が目的変数 $y$ に与える影響の大きさで、 $b$ は変数 $x_1, x_2, \cdots, x_M$ の内容にかかわらず $y$ に影響を与えるバイアスとなる。

### モデルの式変形
バイアス $b$ を ${w_0}{x_0}$ とするとモデルの式は下記のように書き換えられる
$$
\begin{eqnarray}
y &=& {w_1}{x_1} + {w_2}{x_2} + ... + {w_M}{x_M} + b \\
&=& {w_0}{x_0} + {w_1}{x_1} + {w_2}{x_2} + ... + {w_M}{x_M} \\
&=& \begin{bmatrix}
{w_0} & {w_1} & \cdots & {w_M}
\end{bmatrix}
\begin{bmatrix}
{x_0} \\
{x_1} \\
\vdots \\
{x_M}
\end{bmatrix}
= \begin{bmatrix}
{x_0} & {x_1} & \cdots & {x_M}
\end{bmatrix}
\begin{bmatrix}
{w_0} \\
{w_1} \\
\vdots \\
{w_M}
\end{bmatrix}
\end{eqnarray}
$$

ここで
$$
\boldsymbol{x} = \begin{bmatrix}
{x_0} \\
{x_1} \\
\vdots \\
{x_M}
\end{bmatrix},
\boldsymbol{w} = \begin{bmatrix}
{w_0} \\
{w_1} \\
\vdots \\
{w_M}
\end{bmatrix}
$$
とすると
$$
y = \boldsymbol{x}^T\boldsymbol{w} 
$$
と表すことができる

## 損失関数
単回帰分析の時と同様損失関数を実測値 $y_{i}$、予測値 $\hat{y_{i}}$を用いて下記でおく
$$
\mathcal{L} = \sum_{i=1}^{N}{(y_{i} - \hat{y_{i}})^2}
$$

### 損失関数の式変形
$$
\begin{eqnarray}
\mathcal{L} &=& \sum_{i=1}^{N}{(y_{i} - \hat{y_{i}})^2} \\
&=& ({y_1} - \hat{y_1})^2 + ({y_2} - \hat{y_2})^2 + \cdots + ({y_N} - \hat{y_N})^2 \\
&=& \begin{bmatrix}
{{y_1} - \hat{y_1}} & {{y_2} - \hat{y_2}} & \cdots & {{y_N} - \hat{y_N}}
\end{bmatrix}
\begin{bmatrix}
{{y_1} - \hat{y_1}} \\
{{y_2} - \hat{y_2}} \\
\vdots \\
{{y_N} - \hat{y_N}}
\end{bmatrix}
\end{eqnarray}
$$
ここで
$$
\boldsymbol{y} = \begin{bmatrix}
{y_1} \\
{y_2} \\
\vdots \\
{y_N}
\end{bmatrix},
\hat{\boldsymbol{y}} = \begin{bmatrix}
{\hat{y_1}} \\
{\hat{y_2}} \\
\vdots \\
{\hat{y_N}}
\end{bmatrix}
$$
とすると
$$
\begin{bmatrix}
{{y_1} - \hat{y_1}} \\
{{y_2} - \hat{y_2}} \\
\vdots \\
{{y_N} - \hat{y_N}}
\end{bmatrix}
= \boldsymbol{y} - \hat{\boldsymbol{y}}
$$
となるため
$$
\begin{eqnarray}
\mathcal{L} &=& \sum_{i=1}^{N}{(y_{i} - \hat{y_{i}})^2} \\
&=& {(\boldsymbol{y} - \hat{\boldsymbol{y}})^T}{(\boldsymbol{y} - \hat{\boldsymbol{y}})}
\end{eqnarray}
$$
となる

## 損失関数を最小化するパラメータを見つける
$\hat{y_i} = \boldsymbol{x_i}^T\boldsymbol{w_i}$ であるので 損失関数の $\hat{\boldsymbol{y}}$は下記の通り展開できる

$$
\hat{\boldsymbol{y}} = \begin{bmatrix}
{\hat{y_1}} \\
{\hat{y_2}} \\
\vdots \\
{\hat{y_N}}
\end{bmatrix}
= \begin{bmatrix}
{\boldsymbol{x_1}^T{w_1}} \\
{\boldsymbol{x_2}^T{w_2}} \\
\vdots \\
{\boldsymbol{x_N}^T{w_N}}
\end{bmatrix}
= \begin{bmatrix}
{\boldsymbol{x_1}^T} \\
{\boldsymbol{x_2}^T} \\
\vdots \\
{\boldsymbol{x_N}^T}
\end{bmatrix}
\boldsymbol{w}
= \begin{bmatrix}
{x_{10}} & {x_{11}} & {x_{12}} & \cdots & {x_{1M}} \\
{x_{20}} & {x_{21}} & {x_{22}} & \cdots & {x_{2M}} \\
\vdots & \vdots & \vdots & \ddots & \vdots \\
{x_{N0}} & {x_{N1}} & {x_{N2}} & \cdots & {x_{NM}}
\end{bmatrix}
\boldsymbol{w}
$$
ここで
$$
\begin{bmatrix}
{x_{10}} & {x_{11}} & {x_{12}} & \cdots & {x_{1M}} \\
{x_{20}} & {x_{21}} & {x_{22}} & \cdots & {x_{2M}} \\
\vdots & \vdots & \vdots & \ddots & \vdots \\
{x_{N0}} & {x_{N1}} & {x_{N2}} & \cdots & {x_{NM}}
\end{bmatrix} = \boldsymbol{X}
$$
とおくと
$$
\hat{\boldsymbol{y}} = \boldsymbol{X}\boldsymbol{w}
$$
と表せる。すなわち損失関数は
$$
\begin{eqnarray}
\mathcal{L} &=& {(\boldsymbol{y} - \hat{\boldsymbol{y}})^T}{(\boldsymbol{y} - \hat{\boldsymbol{y}})} \\
&=& {(\boldsymbol{y} -  \boldsymbol{X}\boldsymbol{w})^T}{(\boldsymbol{y} -  \boldsymbol{X}\boldsymbol{w})} \\
&=& {(\boldsymbol{y}^T - (\boldsymbol{X}\boldsymbol{w})^T)}{(\boldsymbol{y} -  \boldsymbol{X}\boldsymbol{w})} \\
&=& {(\boldsymbol{y}^T - \boldsymbol{w}^T\boldsymbol{X}^T)}{(\boldsymbol{y} -  \boldsymbol{X}\boldsymbol{w})} \\
&=& {\boldsymbol{y}^T}{\boldsymbol{y}} - {\boldsymbol{y}^T}{\boldsymbol{X}}{\boldsymbol{w}} - {\boldsymbol{w}^T\boldsymbol{X}^T}{\boldsymbol{y}} + {\boldsymbol{w}^T\boldsymbol{X}^T}{\boldsymbol{X}\boldsymbol{w}} \\
&=& {\boldsymbol{y}^T}{\boldsymbol{y}} - 2{\boldsymbol{y}^T}{\boldsymbol{X}}{\boldsymbol{w}} + {\boldsymbol{w}^T\boldsymbol{X}^T}{\boldsymbol{X}\boldsymbol{w}}
\end{eqnarray}
$$
と変形できる。この上で
$$
\frac{\partial}{\partial{\boldsymbol{w}}}\mathcal{L} = \boldsymbol{0}
$$
となる $\boldsymbol{w}$ を算出する

$$
\begin{eqnarray}
\frac{\partial}{\partial{\boldsymbol{w}}}\mathcal{L} &=& \frac{\partial}{\partial{\boldsymbol{w}}}{({\boldsymbol{y}^T}{\boldsymbol{y}} - 2{\boldsymbol{y}^T}{\boldsymbol{X}}{\boldsymbol{w}} + {\boldsymbol{w}^T\boldsymbol{X}^T}{\boldsymbol{X}\boldsymbol{w}})} \\
&=& \frac{\partial}{\partial{\boldsymbol{w}}}{({\boldsymbol{y}^T}{\boldsymbol{y}})} 
- \frac{\partial}{\partial{\boldsymbol{w}}}{(2{\boldsymbol{y}^T}{\boldsymbol{X}}{\boldsymbol{w}})}
+ \frac{\partial}{\partial{\boldsymbol{w}}}{({\boldsymbol{w}^T\boldsymbol{X}^T}{\boldsymbol{X}\boldsymbol{w}})} \\
&=& \boldsymbol{0} - 2{\boldsymbol{X}^T}{\boldsymbol{y}}
 + ({\boldsymbol{X}^T}{\boldsymbol{X}}+({\boldsymbol{X}^T}{\boldsymbol{X}})^T)\boldsymbol{w} \\
&=& - 2{\boldsymbol{X}^T}{\boldsymbol{y}} + 2{\boldsymbol{X}^T}{\boldsymbol{X}}\boldsymbol{w}
\end{eqnarray}
$$

$$
\begin{eqnarray}
- 2{\boldsymbol{X}^T}{\boldsymbol{y}} + 2{\boldsymbol{X}^T}{\boldsymbol{X}}\boldsymbol{w} &=& \boldsymbol{0} \\
{\boldsymbol{X}^T}{\boldsymbol{X}}\boldsymbol{w} &=& {\boldsymbol{X}^T}{\boldsymbol{y}} \\
\boldsymbol{w} = ({\boldsymbol{X}^T}{\boldsymbol{X}})^{-1}{\boldsymbol{X}^T}{\boldsymbol{y}}
\end{eqnarray}
$$

## 実際に求めてみる

In [1]:
import numpy as np

In [2]:
X = np.array([
    [1, 2, 3],
    [1, 2, 5],
    [1, 3, 4],
    [1, 5, 9]
])
y = np.array([
    [1],
    [5],
    [6],
    [8]
])

In [3]:
Xt = X.T
XtX_inv = np.linalg.inv(np.dot(Xt, X))

In [4]:
Xty = np.dot(Xt, y)

In [5]:
w = np.dot(XtX_inv, Xty)
w

array([[-0.14285714],
       [ 0.71428571],
       [ 0.57142857]])

## scikit-learn

In [6]:
from sklearn.linear_model import LinearRegression

In [7]:
model = LinearRegression(fit_intercept=False)
model.fit(X, y)

LinearRegression(fit_intercept=False)

In [8]:
model.coef_

array([[-0.14285714,  0.71428571,  0.57142857]])

In [9]:
model.score(X, y)

0.6923076923076923

In [10]:
x = np.array([
    [1, 3, 6]
])
model.predict(x)

array([[5.42857143]])